### PR TITLE
Adding Admin App Changes

### PR DESCRIPTION
**Pull request by neelavarshad**
## Description
Made changes to the Admin Webapp to mimic the Partner Center look and feel.
Also added the modifications suggested by @code4clouds 

### Homepage
image

### CODE REVIEW

**Comment by code4clouds** [comment]
Page looks great!  The new large menus ... great idea!   

A few small details:  
- Text is all caps
- Text needs to be on the right side of the image.

image

- Add to the Welcome add Welcome to SaaS Accelerator Admin Page (or something along these lines).

Would you post screenshot for the additional menus?

**Comment by neelavarshad** [comment]
### Homepage 
image

## Subscriptions
image

## Plans
image

## Offers 
image

**Changes Added**
1. Made changes suggested by @code4clouds 
2. Changed the tables to mimic Partner Center (I still kept the header the same way, instead of making it small like in Partner Center since its easier to read what is what)
3. Changed the font size for the quicklinks since it looked larger than the image beside it

**Comment by code4clouds** [comment]
One last thing...  Would you mind aligning the Logo to the left with the icons?

image

Other than this... everything else looks good.  How does the dialog boxes look (pop-ups and menus)?

**Comment by neelavarshad** [comment]
## Pop-ups
image

## Plans
image

## Logo
image


## Home 
image


Changes to be made (optionally if time permits):
1. Add links to Partner Center on nav bar

**Review by code4clouds — APPROVED** [review]
Looks good to me...

**Pull request merged**
