### PR TITLE
Feature implementation to support per user pricing plan model

### PR DESCRIPTION
**Pull request by santhoshbomma9**
I have created implementation to support plans on per user model.  Let me know if you would like me to make any changes. Please review before we can complete the merge.  Please let me know your thoughts.
image
image
image
image

### CODE REVIEW

**Comment by code4clouds** [comment]
Hi Santosh, 

Code looks good to me, before we merge... let make sure this wasn't added in the 1.1 branch (Adding @dev-kiranbanda for validation) .

J

**Comment by santhoshbomma9** [comment]
> Hi Santosh,
> 
> Code looks good to me, before we merge... let make sure this wasn't added in the 1.1 branch (Adding @dev-kiranbanda for validation) .
> 
> J

Sure, thanks J!

**Comment by dev-kiranbanda** [comment]
Hi Santosh,

Thanks for your contribution. I checked the enhancement and it looks great. I confirm that we didn't have this in 1.1 so this enhancement is a good extension. 

The only thing that I want to bring to your attention is that we made several improvements w.r.t UI/UX and the change that we have here should be updated to align to what we have in 1.1.

@code4clouds  I propose that we let this one go after we release 1.1. @santhoshbomma9 can then take latest from 1.1 and update the implementation accordingly ( primarily UI and db changes )

**Comment by santhoshbomma9** [comment]
Sure @dev-kiranbanda , we can do that! I will close this one, when is release 1.1?

**Comment by dev-kiranbanda** [comment]
> Sure @dev-kiranbanda , we can do that! I will close this one, when is release 1.1?

@code4clouds - Request your comments.

**Comment by code4clouds** [comment]
Not anymore... Its merged in Master.  I rebased 1.1 dev, just need to approve your PR #22 after you rebase it and we are good to move 1.1 to master.

**Pull request merged**
