### PR TITLE
update app settings small fix and install-instructions align

### PR DESCRIPTION
**Pull request by santhoshbomma9**
minor fixes on instructions and appsettings

### CODE REVIEW

**Comment by santhoshbomma9** [comment]
> I don't think we should be adding that / (slash) at the end of the URL.

Sure, if we aren't adding there, they maybe we should add here when using it?
image

**Comment by code4clouds** [comment]
Typically the URL will not have the / at the end and the code where is reference will have the slash as is {subscriptionBaseURL}/resolve?api .... to indicate is a route within the base url.

**Comment by code4clouds** [comment]
@santhoshbomma9  I also noticed that not using the slash at the end makes your .RESOLVE and .ACTIVE inconsistent.

**Comment by santhoshbomma9** [comment]
> @santhoshbomma9 I also noticed that not using the slash at the end makes your .RESOLVE and .ACTIVE returns (syntax) inconsistent.

And also inconsistent with the appsetting we already have in `Microsoft.Marketplace.SaaS.SDK.CustomerProvisioning` project

**Comment by code4clouds** [comment]
Yeap... @dev-kiranbanda

**Comment by dev-kiranbanda** [comment]
> Yeap... @dev-kiranbanda

Okay, I can remove the / at the end in the config and have "/" prefixed when we build the full URL for the actions like Resolve and like.

If my understanding of the recommendation is correct, I can have the change in my already open PR (if that is okay ).

**Pull request merged**
